// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import Foundation
import MISOTokensComponent
import MISOTokensRaw
import MISOTokensSemantic

// 🧬 Tokens version: 2.7.0 (Wireframe brand)
// 🤖 Generated by Tokenator

extension WireframeThemeBulletListComponentTokensProvider: BulletListComponentTokens {
    /// Has for value token spaces.columnGapSmall (= 8)
    @objc public final var spaceColumnGapBodyLarge: SpaceSemanticToken { spaces.columnGapSmall }
    /// Has for value token spaces.columnGapSmall (= 8)
    @objc public final var spaceColumnGapBodyMedium: SpaceSemanticToken { spaces.columnGapSmall }
    /// Has for value token spaces.paddingBlock2xsmall (= 6)
    @objc public final var spacePaddingBlockBodyLarge: SpaceSemanticToken { spaces.paddingBlock2xsmall }
    /// Has for value token spaces.paddingBlock2xsmall (= 6)
    @objc public final var spacePaddingBlockBodyMedium: SpaceSemanticToken { spaces.paddingBlock2xsmall }
    /// Has for value token DimensionRawTokens._50 (= 4)
    @objc public final var spacePaddingInlineLevel0: SpaceSemanticToken { DimensionRawTokens._50 }
    /// Has for value token DimensionRawTokens._450 (= 36)
    @objc public final var spacePaddingInlineLevel1: SpaceSemanticToken { DimensionRawTokens._450 }
    /// Has for value token DimensionRawTokens._850 (= 68)
    @objc public final var spacePaddingInlineLevel2: SpaceSemanticToken { DimensionRawTokens._850 }
}
