// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import Foundation
import MISOTokensComponent
import MISOTokensSemantic

// 🧬 Tokens version: 2.7.0 (Wireframe brand)
// 🤖 Generated by Tokenator

extension WireframeThemeRadioButtonComponentTokensProvider: RadioButtonComponentTokens {
    /// Has for value token borders.radiusPill (= 2000)
    @objc public final var borderRadius: BorderRadiusSemanticToken { borders.radiusPill }
    /// Has for value token borders.widthNone (= 0)
    @objc public final var borderWidthSelected: BorderWidthSemanticToken { borders.widthNone }
    /// Has for value token borders.widthNone (= 0)
    @objc public final var borderWidthSelectedFocus: BorderWidthSemanticToken { borders.widthNone }
    /// Has for value token borders.widthNone (= 0)
    @objc public final var borderWidthSelectedHover: BorderWidthSemanticToken { borders.widthNone }
    /// Has for value token borders.widthNone (= 0)
    @objc public final var borderWidthSelectedPressed: BorderWidthSemanticToken { borders.widthNone }
    /// Has for value token borders.widthMedium (= 3)
    @objc public final var borderWidthUnselected: BorderWidthSemanticToken { borders.widthMedium }
    /// Has for value token borders.widthMedium (= 3)
    @objc public final var borderWidthUnselectedFocus: BorderWidthSemanticToken { borders.widthMedium }
    /// Has for value token borders.widthMedium (= 3)
    @objc public final var borderWidthUnselectedHover: BorderWidthSemanticToken { borders.widthMedium }
    /// Has for value token borders.widthMedium (= 3)
    @objc public final var borderWidthUnselectedPressed: BorderWidthSemanticToken { borders.widthMedium }
    /// Has for value token sizes.minInteractiveAreaDefault (= 48)
    @objc public final var sizeMaxHeight: SizeSemanticToken { sizes.minInteractiveAreaDefault }
    /// Has for value token sizes.minInteractiveAreaDefault (= 48)
    @objc public final var sizeMinHeight: SizeSemanticToken { sizes.minInteractiveAreaDefault }
    /// Has for value token sizes.minInteractiveAreaDefault (= 48)
    @objc public final var sizeMinWidth: SizeSemanticToken { sizes.minInteractiveAreaDefault }
}
