// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import Foundation
import MISOTokensComponent
import MISOTokensSemantic

// 🧬 Tokens version: 2.7.0 (Wireframe brand)
// 🤖 Generated by Tokenator

extension WireframeThemeSelectInputComponentTokensProvider: SelectInputComponentTokens {
    /// Has for value token dimensions._8xlarge (= 96)
    @objc public final var sizeMinWidth: SizeSemanticToken { dimensions._8xlarge }
}
