// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import Foundation
import MISOTokensComponent
import MISOTokensSemantic

// 🧬 Tokens version: 1.1.0 (Wireframe brand)
// 🤖 Generated by Tokenator

extension WireframeThemeDividerComponentTokensProvider: DividerComponentTokens {
    /// Has for value token borders.widthThin
    @objc public final var borderWidth: BorderWidthSemanticToken { borders.widthThin }
}
