// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import MISOTokensComponent
import MISOTokensSemantic

// 🧬 Tokens version: 1.1.0 (Wireframe brand)
// 🤖 Generated by Tokenator

extension WireframeThemeDividerComponentTokensProvider: DividerComponentTokens {
    /// Has for value token borders.widthThin
    @objc public final var borderWidth: BorderWidthSemanticToken { borders.widthThin }
}
