// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import Foundation
import MISOTokensComponent
import MISOTokensSemantic

// 🧬 Tokens version: 2.7.0 (Wireframe brand)
// 🤖 Generated by Tokenator

extension WireframeThemeAlertMessageComponentTokensProvider: AlertMessageComponentTokens {
    /// Has for value token borders.widthThin (= 1)
    @objc public final var borderWidth: BorderWidthSemanticToken { borders.widthThin }
    /// Has for value token spaces.rowGapNone (= 0)
    @objc public final var spaceRowGapBullet: SpaceSemanticToken { spaces.rowGapNone }
}
