// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import Foundation
import MISOTokensComponent
import MISOTokensSemantic

// 🧬 Tokens version: 2.7.0 (Wireframe brand)
// 🤖 Generated by Tokenator

// swiftlint:disable identifier_name

extension WireframeThemeAccordionComponentTokensProvider: AccordionComponentTokens {
    /// Has for value token spaces.paddingBlock3xlarge (= 28)
    @objc public final var spacePaddingBlockBottomExpandContainerDefault: SpaceSemanticToken { spaces.paddingBlock3xlarge }
    /// Has for value token spaces.paddingBlock2xlarge (= 24)
    @objc public final var spacePaddingBlockBottomExpandContainerSmall: SpaceSemanticToken { spaces.paddingBlock2xlarge }
    /// Has for value token spaces.paddingBlockXsmall (= 8)
    @objc public final var spacePaddingBlockTopExpandContainer: SpaceSemanticToken { spaces.paddingBlockXsmall }
}

// swiftlint:enable identifier_name
