// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import Foundation
import MISOTokensComponent
import MISOTokensSemantic

// 🧬 Tokens version: 2.7.0 (Wireframe brand)
// 🤖 Generated by Tokenator

extension WireframeThemePinCodeInputComponentTokensProvider: PinCodeInputComponentTokens {
    /// Has for value token dimensions._3xlarge (= 56)
    @objc public final var sizeMaxWidth: SizeSemanticToken { dimensions._3xlarge }
    /// Has for value token dimensions._large (= 44)
    @objc public final var sizeMinWidth: SizeSemanticToken { dimensions._large }
    /// Has for value token spaces.columnGapMedium (= 12)
    @objc public final var spaceColumnGapDigitInput: SpaceSemanticToken { spaces.columnGapMedium }
}
