// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import Foundation
import MISOTokensComponent
import MISOTokensSemantic

// 🧬 Tokens version: 2.7.0 (Wireframe brand)
// 🤖 Generated by Tokenator

// swiftlint:disable identifier_name

extension WireframeThemeTypographyComponentTokensProvider: TypographyComponentTokens {
    /// Has for value token colors.contentBrandSecondary (= light: "#DB2345FF" / dark: "#F66F7DFF")
    @objc public final var colorContentMarker: MultipleColorSemanticToken { colors.contentBrandSecondary }
    /// Has for value token true
    @objc public final var headingLargeMarker: Bool { true }
    /// Has for value token spaces.paddingBlockNone (= 0)
    @objc public final var spacePaddingBlockBottomHeadingLargeMarker: SpaceSemanticToken { spaces.paddingBlockNone }
    /// Has for value token spaces.paddingBlock3xsmall (= 4)
    @objc public final var spacePaddingBlockTopHeadingLargeMarker: SpaceSemanticToken { spaces.paddingBlock3xsmall }
}

// swiftlint:enable identifier_name
