// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

#if !os(watchOS) && !os(tvOS)
import SwiftUI

/// The data to use to populate the picker of ``MISORadioItem`` objects.
/// Each property in this ``MISORadioPickerData`` is used to define the suitable ``MISORadioItem``.
///
/// - Since: 0.14.0
public struct MISORadioPickerData<Tag> where Tag: Hashable {

    /// The identifier, supposed to be unique, to discriminate the element.
    /// This value will be exposed as selection inside the ``MISORadioPicker``.
    let tag: Tag

    /// The label, main text, the ``MISORadioItem`` must have
    let label: String

    /// An optional additional label the ``MISORadioItem`` can have
    let extraLabel: String?

    /// A description the ``MISORadioItem`` can have
    let description: String?

    /// An optional image the ``MISORadioItem`` can have, encapsulating the asset, flip flag and rendering mode
    let icon: MISOImage?

    /// Define if the ``MISORadioItem`` is outlined or not
    let isOutlined: Bool

    /// Define if the ``MISORadioItem`` is reversed or not
    let isReversed: Bool

    /// Define if the ``MISORadioItem`` is in error context or not
    let isError: Bool

    /// Define if the ``MISORadioItem`` is in read only mode or not
    let isReadOnly: Bool

    /// Define if the ``MISORadioItem`` has a divider not
    let hasDivider: Bool

    /// If needed, and because the items in the ``MISORadioPicker`` are generated by the picker, the accesibility identifier to add to the generated item.
    /// Can be useful for automated tests for examples or anything else.
    /// By default is nil as the logic of identifiers is in the hand of the users.
    let accessibilityIdentifier: String?

    /// Defines the data to use to define the radio buttons (``MISORadioItem``)
    ///
    /// ```swift
    ///     MISORadioPickerData(tag: "option1", label: "Option 1")
    ///
    ///     MISORadioPickerData(tag: "option2",
    ///                         label: "Option 2",
    ///                         image: MISOImage(asset: Image(systemName: "flame")))
    ///
    ///     // Raw (non-tinted) image:
    ///     MISORadioPickerData(tag: "option3",
    ///                         label: "Option 3",
    ///                         image: MISOImage(asset: Image(decorative: "il_brand"), renderingMode: .original))
    /// ```
    ///
    /// - Parameters:
    ///    - tag: a value to discriminate one radio to another
    ///    - label: the mandatory text to add to ``MISORadioItem``
    ///    - extraLabel: An optional additional text, default set to nil
    ///    - description: Another optional text, a description, default set to nil
    ///    - image: An optional ``MISOImage`` encapsulating the asset, its flip flag and its rendering mode. Default set to `nil`.
    ///    - isOutlined: True to outline the ``MISORadioItem``, false otherwise (default)
    ///    - isReversed: True to use to reversed layout of the ``MISORadioItem``, false otherwise (default)
    ///    - isError: True if in an error context, false otherwise (default)
    ///    - isReadOnly: True if read only, false otherwise (default)
    ///    - hasDivider: True if a divider must be added for the current ``MISORadioItem``, false otherwise (default)
    ///    - accessibilityIdentifier: The accessibility identifier to add to the item, nil by default
    ///
    /// **Remark: If `label`, `extraLabel` and `description` strings are wording keys from strings catalog stored in `Bundle.main`, they are
    /// automatically localized. Else, prefer to provide the localized string if key is stored in another bundle.**
    public init(tag: Tag,
                label: String,
                extraLabel: String? = nil,
                description: String? = nil,
                image: MISOImage? = nil,
                isOutlined: Bool = false,
                isReversed: Bool = false,
                isError: Bool = false,
                isReadOnly: Bool = false,
                hasDivider: Bool = false,
                accessibilityIdentifier: String? = nil)
    {
        self.tag = tag
        self.label = label
        self.extraLabel = extraLabel
        self.description = description
        icon = image
        self.isOutlined = isOutlined
        self.isReversed = isReversed
        self.isError = isError
        self.isReadOnly = isReadOnly
        self.hasDivider = hasDivider
        self.accessibilityIdentifier = accessibilityIdentifier
    }
}

#endif
