retain_public: true
retain_objc_accessible: true
targets:
- MISO
- MISOComponents
- MISOFoundations
- MISOModules
- MISOThemesContract
- MISOThemesWireframe
- MISOTokensComponent
- MISOTokensRaw
- MISOTokensSemantic
- TestsUtils
