// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensRaw

// 🧬 Tokens version: 1.5.0 (Core Wireframe)
// 🤖 Generated by Tokenator

extension WireframeBrandFontRawTokens {
    /// Has for value "Shantell Sans"
    public static let familyDefault: FontFamilyRawToken = "Shantell Sans"
}
