// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **effects**.
/// It defines all ``EffectSemanticToken`` a theme must have.
/// Any effect semantic token must be declared there.
///
/// - Since: 0.22.0
public protocol EffectSemanticTokens {

    var blurBackdrop: EffectSemanticToken { get }
    var blurDrag: EffectSemanticToken { get }
}

// swiftlint:enable missing_docs
