// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **opacity.**
/// It defines all ``OpacitySemanticToken`` a theme must have.
/// Any opacity semantic token must be declared there as providers like `WireframeThemeOpacitySemanticTokensProvider` will then expose them through `MISOTheme`.
///
/// - Since: 0.8.0
public protocol OpacitySemanticTokens {

    var invisible: OpacitySemanticToken { get }
    var weakest: OpacitySemanticToken { get }
    var weaker: OpacitySemanticToken { get }
    var weak: OpacitySemanticToken { get }
    var medium: OpacitySemanticToken { get }
    var strong: OpacitySemanticToken { get }
    var opaque: OpacitySemanticToken { get }
    var disabled: OpacitySemanticToken { get }
}

// swiftlint:enable missing_docs
