// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable identifier_name

/// Declares all component tokens for accordion components like `MISOAccordion`
/// Used for tokens providers like `WireframeThemeAccordionComponentTokensProvider` etc.
///
/// - Since: 3.0.0
public protocol AccordionComponentTokens {

    var spacePaddingBlockBottomExpandContainerSmall: SpaceSemanticToken { get }
    var spacePaddingBlockBottomExpandContainerDefault: SpaceSemanticToken { get }
    var spacePaddingBlockTopExpandContainer: SpaceSemanticToken { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable identifier_name
