// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for alert components like `MISOAlertMessage`
/// Used for tokens providers like `WireframeThemeAlertMessageComponentTokensProvider` etc.
///
/// - Since: 3.0.0
public protocol AlertMessageComponentTokens {

    var borderWidth: BorderWidthSemanticToken { get }
    var spaceRowGapBullet: SpaceSemanticToken { get }
}

// swiftlint:enable missing_docs
