// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for alert components.
/// Used for tokens providers like `WireframeThemeAlertComponentTokensProvider` etc.
///
/// - Since:1.2.0
public protocol AlertComponentTokens {

    // MARK: - Borders

    var borderRadiusDefault: BorderRadiusSemanticToken { get }
    var borderRadiusRounded: BorderRadiusSemanticToken { get }

    // MARK: - Spaces

    var spacePaddingBlock: SpaceSemanticToken { get }
    var spacePaddingBlockBottomContent: SpaceSemanticToken { get }
    var spacePaddingInline: SpaceSemanticToken { get }
    var spaceColumnGap: SpaceSemanticToken { get }
    var spaceColumnGapAction: SpaceSemanticToken { get }
    var spaceInsetProgressIndicator: SpaceSemanticToken { get }
    var spaceRowGap: SpaceSemanticToken { get }

    // MARK: - Size

    var sizeAsset: SizeSemanticToken { get }
    var sizeMinHeight: SizeSemanticToken { get }
    var sizeMinHeightBottomAction: SizeSemanticToken { get }
    var sizeMinWidth: SizeSemanticToken { get }
}

// swiftlint:enable missing_docs
