// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for badge components like `MISOBadgeStandard`, `MISOBadgeIcon` and `MISOBadgeCount`.
/// Use for tokens providers like `WireframeThemeBadgeComponentTokensProvider`.
///
/// - Since: 0.10.0
public protocol BadgeComponentTokens {

    // MARK: - Sizes

    var sizeXsmall: SizeSemanticToken { get }
    var sizeSmall: SizeSemanticToken { get }
    var sizeMedium: SizeSemanticToken { get }
    var sizeLarge: SizeSemanticToken { get }

    // MARK: - Spaces

    var spaceInsetXsmall: SpaceSemanticToken { get }
    var spaceInsetSmall: SpaceSemanticToken { get }
    var spaceInsetMediumLarge: SpaceSemanticToken { get }
    var spacePaddingInlineMedium: SpaceSemanticToken { get }
    var spacePaddingInlineLarge: SpaceSemanticToken { get }
}

// swiftlint:enable missing_docs
