// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable identifier_name

/// Declares all component tokens for bar components l
/// Use for tokens providers like `WireframeThemeBarComponentTokensProvider`.
///
/// - Since: 0.22.0
public protocol BarComponentTokens {

    // MARK: - Colors

    var colorAccent: MultipleColorSemanticToken { get }
    var colorBgOpaque: MultipleColorSemanticToken { get }
    var colorBgTranslucent: MultipleColorSemanticToken { get }
    var colorContentSelectedEnabled: MultipleColorSemanticToken { get }
    var colorContentSelectedHover: MultipleColorSemanticToken { get }
    var colorContentSelectedPressed: MultipleColorSemanticToken { get }
    var colorContentSelectedFocus: MultipleColorSemanticToken { get }
    var colorContentUnselectedEnabled: MultipleColorSemanticToken { get }
    var colorContentUnselectedHover: MultipleColorSemanticToken { get }
    var colorContentUnselectedPressed: MultipleColorSemanticToken { get }
    var colorContentUnselectedFocus: MultipleColorSemanticToken { get }
    var colorContentOnAccent: MultipleColorSemanticToken { get }
    var colorBorderBadge: MultipleColorSemanticToken { get }
    var colorCurrentIndicatorCustomSelectedEnabled: MultipleColorSemanticToken { get }
    var colorCurrentIndicatorCustomSelectedHover: MultipleColorSemanticToken { get }
    var colorCurrentIndicatorCustomSelectedPressed: MultipleColorSemanticToken { get }
    var colorCurrentIndicatorCustomSelectedFocus: MultipleColorSemanticToken { get }

    // MARK: - Opacities

    var opacityCurrentIndicatorCustom: OpacitySemanticToken { get }

    // MARK: - Effects

    var effectBgBlur: EffectSemanticToken { get }

    // MARK: - Borders

    var borderRadiusCurrentIndicatorCustomTop: BorderRadiusSemanticToken { get }
    var borderRadiusCurrentIndicatorCustomBottom: BorderRadiusSemanticToken { get }

    // MARK: - Sizes

    var sizeWidthCurrentIndicatorCustomTop: SizeSemanticToken { get }
    var sizeWidthCurrentIndicatorCustomBottom: SizeSemanticToken { get }
    var sizeHeightCurrentIndicatorCustom: SizeSemanticToken { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable identifier_name
