// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for bullet list components like `MISOBulletList`
/// Use for tokens providers like `WireframeThemeBulletListComponentTokensProvider`.
///
/// - Since: 0.10.0
public protocol BulletListComponentTokens {

    // MARK: - Spaces

    var spaceColumnGapBodyLarge: SpaceSemanticToken { get }
    var spaceColumnGapBodyMedium: SpaceSemanticToken { get }
    var spacePaddingBlockBodyLarge: SpaceSemanticToken { get }
    var spacePaddingBlockBodyMedium: SpaceSemanticToken { get }
    var spacePaddingInlineLevel0: SpaceSemanticToken { get }
    var spacePaddingInlineLevel1: SpaceSemanticToken { get }
    var spacePaddingInlineLevel2: SpaceSemanticToken { get }
}

// swiftlint:enable missing_docs
