// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for categorical tag components like `MISOCategoricalTag`
/// Used for tokens providers like `WireframeThemeCategoricalTagComponentTokensProvider` etc.
///
/// - Since: 3.0.0
public protocol CategoricalTagComponentTokens {

    var colorBgCategory1: MultipleColorSemanticToken { get }
    var colorBgCategory2: MultipleColorSemanticToken { get }
    var colorBgCategory3: MultipleColorSemanticToken { get }
    var colorBgCategory4: MultipleColorSemanticToken { get }
    var colorBgCategory5: MultipleColorSemanticToken { get }
    var colorContent: MultipleColorSemanticToken { get }
}

// swiftlint:enable missing_docs
