// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable identifier_name

/// Declares all component tokens for components using icons (like `MISOTag`).
/// Use for tokens providers like `WireframeThemeIconComponentTokensProvider`.
///
/// - Since: 0.20.0
public protocol IconComponentTokens {

    var colorContentStatusWarningExternalShape: MultipleColorSemanticToken { get }
    var colorContentStatusWarningInternalShape: MultipleColorSemanticToken { get }
    var colorContentStatusWarningInverseExternalShape: MultipleColorSemanticToken { get }
    var colorContentStatusWarningInverseInternalShape: MultipleColorSemanticToken { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable identifier_name
