// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for tags components like `MISOInputTag`
/// Used for tokens providers like `WireframeThemeInputTagComponentTokensProvider`.
///
/// - Since: 0.17.0
public protocol InputTagComponentTokens {

    // MARK: - Colors

    var colorBgEnabled: MultipleColorSemanticToken { get }
    var colorBgHover: MultipleColorSemanticToken { get }
    var colorBgPressed: MultipleColorSemanticToken { get }
    var colorBgFocus: MultipleColorSemanticToken { get }
    var colorContentEnabled: MultipleColorSemanticToken { get }
    var colorContentHover: MultipleColorSemanticToken { get }
    var colorContentPressed: MultipleColorSemanticToken { get }
    var colorContentFocus: MultipleColorSemanticToken { get }
    var colorBorderEnabled: MultipleColorSemanticToken { get }
    var colorBorderHover: MultipleColorSemanticToken { get }
    var colorBorderPressed: MultipleColorSemanticToken { get }
    var colorBorderFocus: MultipleColorSemanticToken { get }

    // MARK: - Borders

    var borderWidthDefault: BorderWidthSemanticToken { get }
    var borderWidthDefaultInteraction: BorderWidthSemanticToken { get }
}

// swiftlint:enable missing_docs
