// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for links components like `MISOLink` in **monochrome mode**.
/// Used for tokens providers like `WireframeThemeLinkComponentTokensProvider`.
///
/// - Since: 0.16.0
public protocol LinkMonoComponentTokens {

    var monoColorContentEnabled: MultipleColorSemanticToken { get }
    var monoColorContentHover: MultipleColorSemanticToken { get }
    var monoColorContentPressed: MultipleColorSemanticToken { get }
    var monoColorContentDisabled: MultipleColorSemanticToken { get }
    var monoColorContentFocus: MultipleColorSemanticToken { get }
}

// swiftlint:enable missing_docs
