// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for links components like `MISOLink`
/// Use for tokens providers like `WireframeThemeLinkComponentTokensProvider`.
///
/// - Since: 0.10.0
public protocol LinkComponentTokens {

    // MARK: - Sizes

    var sizeMinHeightSmall: SizeSemanticToken { get }
    var sizeMinHeightDefault: SizeSemanticToken { get }
    var sizeMinHeightCompactDensity: SizeSemanticToken { get }
    var sizeMinWidthSmall: SizeSemanticToken { get }
    var sizeMinWidth: SizeSemanticToken { get }
    var sizeIconSmall: SizeSemanticToken { get }
    var sizeIconDefault: SizeSemanticToken { get }

    // MARK: - Colors

    var colorContentEnabled: MultipleColorSemanticToken { get }
    var colorContentHover: MultipleColorSemanticToken { get }
    var colorContentPressed: MultipleColorSemanticToken { get }
    var colorContentFocus: MultipleColorSemanticToken { get }
    var colorChevronEnabled: MultipleColorSemanticToken { get }
    var colorChevronHover: MultipleColorSemanticToken { get }
    var colorChevronPressed: MultipleColorSemanticToken { get }
    var colorChevronFocus: MultipleColorSemanticToken { get }

    // MARK: - Spaces

    var spacePaddingInline: SpaceSemanticToken { get }
    var spacePaddingBlockSmall: SpaceSemanticToken { get }
    var spacePaddingBlockCompactDensityDefault: SpaceSemanticToken { get }
    var spacePaddingBlockCompactDensitySmall: SpaceSemanticToken { get }
    var spacePaddingBlockDefault: SpaceSemanticToken { get }
    var spaceColumnGapIconSmall: SpaceSemanticToken { get }
    var spaceColumnGapChevronSmall: SpaceSemanticToken { get }
    var spaceColumnGapIconDefault: SpaceSemanticToken { get }
    var spaceColumnGapChevronDefault: SpaceSemanticToken { get }

    /*

     ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣄⠀⠀⠀⠀⠀⠀
     ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣤⣤⣄⠀⠀⠀⠀⠀⠀⣿⣆⠀⠀⠀⠀⠀
     ⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣤⠀⠀⠀⠀⣿⣿⡄⠀⠀⠀⠀
     ⠀⠀⠀⠀⣠⡿⠿⠻⢿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⢹⣿⡇⠀⠀⠀⠀
     ⠀⠀⠀⠀⣀⣤⣶⡀⠀⠻⢛⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠈⣿⣷⠀⠀⠀⠀
     ⠀⠀⢠⣾⣿⣿⣿⣿⡦⣼⣯⣵⣿⣿⣿⣿⣷⣦⡀⠀⠀⠀⢹⣿⠀⠀⠀⠀
     ⠀⢠⣿⣿⣿⣿⣿⣿⡿⠿⢿⣿⣿⣿⣿⣿⡿⣿⣿⣦⣀⢀⡘⣿⡇⠀⠀⠀
     ⠀⣾⣿⣿⣿⣿⡟⠉⠀⠀⣾⣿⣿⣿⣿⠟⠁⠀⠉⠻⣿⣿⣿⣿⣧⣠⣶⠄
     ⢰⣿⣿⣿⡿⠋⠀⠀⠀⢀⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠙⠻⣿⣿⣿⡟⠁⠀
     ⢸⣿⡿⠋⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣄⠀⠀⠀⠀⠀⠀⠙⢻⡃⠀⠀
     ⠀⠁⠀⠀⠀⠀⠀⠀⣾⣿⣿⠿⣿⡿⢿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠘⠃⠀⠀
     ⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⡇⠀⠀⠀⠀⠙⢿⣿⣶⣶⣤⠀⠀⠀⠀⠀⠀⠀
     ⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⡟⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀
     ⠀⠀⠀⠀⠀⠀⠀⠀⣻⣿⣿⠀⠀⠀⠀⠀⠀⠀⠉⢻⣿⣿⣇⠀⠀⠀⠀⠀
     ⠀⠀⠀⠀⠀⠀⢰⣾⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⣿⣿⣦⠀⠀⠀⠀
     ⠀⠀⠀⠀⠀⠀⠈⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠿⠿⠿⠀⠀⠀⠀

     */
}

// swiftlint:enable missing_docs
