// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for input components like `MISOQuantityInput`
/// Used for tokens providers like `WireframeThemeQuantityInputComponentTokensProvider`.
///
/// - Since: 0.17.0
public protocol QuantityInputComponentTokens {

    // MARK: - Spaces

    var spaceColumnGapDefault: SpaceSemanticToken { get }
    var spaceColumnGapLeadingIcon: SpaceSemanticToken { get }
    var spaceColumnGapQuantitySelector: SpaceSemanticToken { get }

    // MARK: - Sizes

    var sizeMinWidth: SizeSemanticToken { get }
    var sizeMaxWidth: SizeSemanticToken { get }
}

// swiftlint:enable missing_docs
