// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for radio button components like `MISORadioButton` and `MISORadioButtonItem`.
/// Use for tokens providers like `WireframeThemeRadioButtonComponentTokensProvider`.
///
/// - Since: 0.12.0
public protocol RadioButtonComponentTokens {

    // MARK: - Sizes

    var sizeMaxHeight: SizeSemanticToken { get }
    var sizeMinHeight: SizeSemanticToken { get }
    var sizeMinWidth: SizeSemanticToken { get }

    // MARK: - Borders

    var borderRadius: BorderRadiusSemanticToken { get }
    var borderWidthSelected: BorderWidthSemanticToken { get }
    var borderWidthSelectedFocus: BorderWidthSemanticToken { get }
    var borderWidthSelectedHover: BorderWidthSemanticToken { get }
    var borderWidthSelectedPressed: BorderWidthSemanticToken { get }
    var borderWidthUnselected: BorderWidthSemanticToken { get }
    var borderWidthUnselectedFocus: BorderWidthSemanticToken { get }
    var borderWidthUnselectedHover: BorderWidthSemanticToken { get }
    var borderWidthUnselectedPressed: BorderWidthSemanticToken { get }
}

// swiftlint:enable missing_docs
