// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for input components like `MISOTextArea`
/// Used for tokens providers like `WireframeThemeTextAreaComponentTokensProvider`.
///
/// - Since: 0.17.0
public protocol TextAreaComponentTokens {

    var spacePaddingBlock: SpaceSemanticToken { get }
    var spacePaddingBlockTopEmpty: SpaceSemanticToken { get }
    var spacePaddingBlockTrailingContainer: SpaceSemanticToken { get }
    var spacePaddingBlockEmptyTrailingContainer: SpaceSemanticToken { get }

    var sizeMinHeightInput: SizeSemanticToken { get }
    var sizeMaxHeightInput: SizeSemanticToken { get }
    var sizeMaxHeightAssetsContainer: SizeSemanticToken { get }
    var sizeMaxWidth: SizeSemanticToken { get }
}

// swiftlint:enable missing_docs
