// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for input components like `MISOTextInput`
/// Use for tokens providers like `WireframeThemeTextInputComponentTokensProvider`.
///
/// - Since: 0.17.0
public protocol TextInputComponentTokens {

    // MARK: - Sizes

    var sizeLeadingIcon: SizeSemanticToken { get }
    var sizeCountrySelectorFlagHeight: SizeSemanticToken { get }
    var sizeVerticalDividerHeight: SizeSemanticToken { get }
    var sizeLabelMaxHeight: SizeSemanticToken { get }
    var sizeMinHeight: SizeSemanticToken { get }
    var sizeMinWidth: SizeSemanticToken { get }
    var sizeMaxWidth: SizeSemanticToken { get }

    // MARK: - Colors

    var colorBorderEnabled: MultipleColorSemanticToken { get }
    var colorBorderHover: MultipleColorSemanticToken { get }
    var colorBorderFocus: MultipleColorSemanticToken { get }
    var colorBorderLoading: MultipleColorSemanticToken { get }

    // MARK: - Borders

    var borderRadiusDefault: BorderRadiusSemanticToken { get }
    var borderRadiusRounded: BorderRadiusSemanticToken { get }
    var borderWidthDefault: BorderWidthSemanticToken { get }
    var borderWidthFocus: BorderWidthSemanticToken { get }

    // MARK: - Spaces

    var spacePaddingInlineDefault: SpaceSemanticToken { get }
    var spacePaddingInlineTrailingAction: SpaceSemanticToken { get }
    var spacePaddingInlineCountrySelectorStart: SpaceSemanticToken { get }
    var spacePaddingInlineCountrySelectorEnd: SpaceSemanticToken { get }
    var spacePaddingBlockDefault: SpaceSemanticToken { get }
    var spacePaddingBlockTopHelperText: SpaceSemanticToken { get }
    var spaceColumnGapDefault: SpaceSemanticToken { get }
    var spaceColumnGapInlineText: SpaceSemanticToken { get }
    var spaceColumnGapTrailingErrorAction: SpaceSemanticToken { get }
    var spaceColumnGapLabelAsterisk: SpaceSemanticToken { get }
    var spaceColumnGapLabelSmallAsterisk: SpaceSemanticToken { get }
    var spaceRowGapLabelInput: SpaceSemanticToken { get }
}

// swiftlint:enable missing_docs
