// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for tags components like `MISOToast`
/// Used for tokens providers like `WireframeThemeToastComponentTokensProvider`.
///
/// - Since: 3.0.0
public protocol ToastComponentTokens {

    // MARK: - Borders

    var borderRadiusMedia: BorderRadiusSemanticToken { get }
    var borderRadiusMediaRounded: BorderRadiusSemanticToken { get }

    // MARK: - Sizes

    var sizeAssetLarge: SizeSemanticToken { get }
    var sizeAssetMedium: SizeSemanticToken { get }
    var sizeAssetSmall: SizeSemanticToken { get }
}

// swiftlint:enable missing_docs
