// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable identifier_name

/// Declares all component tokens for input components like `MISOText`
/// Use for tokens providers like `WireframeThemeTypographyComponentTokensProvider`.
///
/// - Since: 3.0.0
public protocol TypographyComponentTokens {

    var spacePaddingBlockTopHeadingLargeMarker: SpaceSemanticToken { get }
    var spacePaddingBlockBottomHeadingLargeMarker: SpaceSemanticToken { get }
    var colorContentMarker: MultipleColorSemanticToken { get }
    var headingLargeMarker: Bool { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable identifier_name
