// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

#if !os(watchOS) && !os(tvOS)
import SwiftUI

/// The data to use to populate the picker of ``OUDSFilterChip`` objects.
/// Each property in this ``OUDSChipPickerData`` is used to define the suitable ``OUDSFilterChip``.
///
/// - Since: 0.17.0
public struct OUDSChipPickerData<Tag> where Tag: Hashable {

    /// The identifier, supposed to be unique, to discriminate the element.
    /// This value will be exposed as selection inside the ``OUDSChipPicker``.
    let tag: Tag

    /// The layout of the ``OUDSFilterChip``
    let layout: Layout

    /// If needed, and because the items in the ``OUDSChipPicker`` are generated by the picker, the accessibility identifier to add to the generated item.
    /// Can be useful for automated tests for examples or anything else.
    /// By default is nil as the logic of identifiers is in the hand of the users.
    let accessibilityIdentifier: String?

    /// The layout of the ``OUDSFilterChip``.
    ///
    /// **Remark: For texts, strings are wording keys from strings catalog stored in `Bundle.main`, they are automatically localized. Else, prefer to
    /// provide the localized string if key is stored in another bundle.**
    /// - Since: 0.17.0
    @frozen public enum Layout {
        /// Layout with text only
        case text(text: String)

        /// Layout with image
        case image(image: MISOImage)

        /// Layout with text and image.
        case textAndImage(text: String, image: MISOImage)

        // MARK: - MISOImage factories

        /// Creates an icon-only layout from an ``MISOImage``.
        ///
        /// ```swift
        ///     OUDSChipPickerData(tag: "a",
        ///                        layout: .image(MISOImage(asset: Image("ic_heart")),
        ///                                       accessibilityLabel: "Heart"))
        ///
        ///     // Raw (non-tinted) image:
        ///     OUDSChipPickerData(tag: "b",
        ///                        layout: .image(MISOImage(asset: Image("ic_brand"), renderingMode: .original),
        ///                                       accessibilityLabel: "Brand"))
        /// ```
        ///
        /// - Parameters:
        ///    - image: An ``MISOImage`` encapsulating the asset and its rendering mode
        ///    - accessibilityLabel: The text to vocalize with Voice Over describing the chip
        @MainActor public static func icon(_ image: MISOImage, accessibilityLabel: String) -> Layout {
            precondition(image.image != nil, "OUDSChipPickerData.Layout.icon(_:accessibilityLabel:) requires a reliable MISOImage")
            // swiftlint:disable:next force_unwrapping
            let newOudsImage = MISOImage(asset: image.image!, accessibilityLabel: accessibilityLabel, renderingMode: image.renderingMode)
            return .image(image: newOudsImage)
        }

        /// Creates a text + icon layout from an ``MISOImage``.
        ///
        /// ```swift
        ///     OUDSChipPickerData(tag: "a",
        ///                        layout: .textAndImage("Label",
        ///                                             image: MISOImage(asset: Image("ic_heart"))))
        ///
        ///     // Raw (non-tinted) image:
        ///     OUDSChipPickerData(tag: "b",
        ///                        layout: .textAndImage("Brand",
        ///                                             image: MISOImage(asset: Image("ic_brand"),
        ///                                                              renderingMode: .original)))
        /// ```
        ///
        /// - Parameters:
        ///    - text: The text to display in the chip
        ///    - image: An ``MISOImage`` encapsulating the asset and its rendering mode
        @MainActor public static func textAndIcon(_ text: String, image: MISOImage) -> Layout {
            precondition(image.image != nil, "OUDSChipPickerData.Layout.textAndIcon(text:image:) requires a reliable MISOImage")
            return .textAndImage(text: text, image: image)
        }
    }

    /// Defines the data to use to define the chip (``OUDSFilterChip``)
    ///
    /// ```swift
    ///     OUDSChipPickerData(tag: "option1", layout: .text(text: "Option 1"))
    /// ```
    ///
    /// - Parameters:
    ///    - tag: A value to discriminate one chip to another
    ///    - layout: The layout of the ``OUDSFilterChip``
    ///    - accessibilityIdentifier: The accessibility identifier to add to the item, nil by default
    public init(tag: Tag,
                layout: Layout,
                accessibilityIdentifier: String? = nil)
    {
        self.tag = tag
        self.layout = layout
        self.accessibilityIdentifier = accessibilityIdentifier
    }
}
#endif
