// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

import Foundation
import MISOTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

// swiftlint:disable line_length

/// Defines provider objects for elevation semantic tokens but "multiple", i.e. tokens with values depending to color schemes.
/// These values can be overridden inside `WireframeThemeElevationSemanticTokensProvider` subclasses (in extensions or not, in the same module or not) thanks to the `@objc open` combination.
extension WireframeThemeElevationSemanticTokensProvider: ElevationMultipleSemanticTokens {

    public var colorElevated: ElevationMultipleColorSemanticToken { MultipleColorSemanticToken(light: colorElevatedLight, dark: colorElevatedDark) }

    public var colorRaised: ElevationMultipleColorSemanticToken { MultipleColorSemanticToken(light: colorRaisedLight, dark: colorRaisedDark) }

    public var colorDrag: ElevationMultipleColorSemanticToken { MultipleColorSemanticToken(light: colorDragLight, dark: colorDragDark) }

    public var colorEmphasized: ElevationMultipleColorSemanticToken { MultipleColorSemanticToken(light: colorEmphasizedLight, dark: colorEmphasizedDark) }

    public var colorSticky: ElevationMultipleColorSemanticToken { MultipleColorSemanticToken(light: colorStickyLight, dark: colorStickyDark) }
}

// swiftlint:enable line_length
