// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

// [File not generated by the tokenator]
// Create an issue for update https://github.com/Orange-OpenSource/miso-ios/issues/new?template=token_update.yml

extension ColorModeRawTokens {

    /// Related to the light mode color scheme
    public static let light: ColorModeRawToken = "light"

    /// Related to the dark mdoe color scheme
    public static let dark: ColorModeRawToken = "dark"

    /// Related to a light monochrome mode
    public static let monochromeLight: ColorModeRawToken = "monoLight"

    /// Related to a dark monochrome mode
    public static let monochromeDark: ColorModeRawToken = "monoDark"

    /// The component in use does not have a defined color mode
    public static let undefined: ColorModeRawToken = "⛔️"
}
