// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

// 🧬 Tokens version: 1.11.0 (Core MISO)
// 🤖 Generated by Tokenator

extension EffectRawTokens {
    /// Has for value 8
    public static let blur80: EffectRawToken = 8
    /// Has for value 32
    public static let blur320: EffectRawToken = 32
    /// Has for value 48
    public static let blur480: EffectRawToken = 48
}
