// SPDX-FileCopyrightText: Copyright (c) Orange SA, Pierre-Yves Lapersonne
// SPDX-License-Identifier: MIT

/// Defined as the group of all **raw tokens** related to **colors**.
/// ``ColorRawTokens`` are tokens to use to define *colors* of components thants to ``ColorRawToken`` type.
/// Some of these colors are "raw", and others have transparency effects.
/// This enum contains also the shared colors, i.e. colors exposed to any theme.
/// Some colors related to a specific brand can be defined elsewhere, e.g. in `WireframeBrandColorRawTokens`.
///
/// - Since: 0.8.0
@frozen public enum ColorRawTokens {

    // Values are defined in *ColorRawTokens+Values.swift* file and generated by the tokenator.
    // Primitive types such as  `String` must be used to as to allow to use `@objc` keywords in extensions for overriding.
    // Such tokens are packed in a _Swift enum_ so as to gather them in one object with the suitable namespace and avoid to have just constants in nothing else
    //  (i.e. publicly accessible from everywhere). More optimized than struct.

    // ଘ( ･ω･)_/ﾟ･:*:･｡☆
    // Note: So as to help the tokenator, the values have been added in the Values folder
    // This trick helps also to write documentation for these tokens as the tokenator cannot generate documentation
}
